apiVersion: v1
kind: Service
metadata:
  name: primeiro-servico
  labels:
    app: primeiro-servico
    service: primeiro-servico
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 5000
  selector:
    app: primeiro-servico
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: primeiro-servico
  labels:
    account: primeiro-servico
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primeiro-servico
  labels:
    app: primeiro-servico
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primeiro-servico
      version: v1
  template:
    metadata:
      labels:
        app: primeiro-servico
        version: v1
    spec:
      serviceAccountName: primeiro-servico
      containers:
      - name: primeiro-servico
        image: primeiro:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: vs-primeiro-servico
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - guilda-gateway
#   http:
#     - match:
#         - uri:
#             prefix: /first
#       route:
#         - destination:
#             host: primeiro-servico
#             port:
#               number: 5000
