apiVersion: v1
kind: Service
metadata:
  name: primeiro-servico
  namespace: poc
  labels:
    app: primeiro-servico
    service: primeiro-servico
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 5000
  selector:
    app: primeiro-servico